#!/bin/bash
IP=192.168.1.101
IP=$(ip addr show dev wlp2s0|grep inet|grep -v inet6|grep -v 127.0.0.1|cut -f6 -d' '|cut -f1 -d/)
URL=http://$IP:9991/
echo $URL | qr
python3 -m http.server 9991 --bind $IP

